#include <GL\glut.h>
#include <Windows.h>
#include "vectors.h"
#include "math.h"
#include <math.h>
#include <cstdlib>
#include <ctime>
#include <string.h>
#include <deque>
#include <iostream>
#include <thread>
#include <time.h>
#include <chrono>